notifications:
  email:
    - et@markuper.com

language: php
cache: composer

php:
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --dev

script: phpunit
